### ISSUE TITLE
Remove implicit `window` dependency

### ISSUE THREAD

**Issue by NathanWalker** [CodeSequence/ngrx-store-router#3]
I'm working on NativeScript + Angular2 integration with `ngrx` and would like to use this reducer.
Ironically before I knew this existed (just came across it today), I ended up coding something almost identical here:
https://github.com/NathanWalker/angular2-seed-advanced/blob/master/src/frameworks/core.framework/state/route.reducer.ts
Used here:
https://github.com/NathanWalker/angular2-seed-advanced/blob/master/src/frameworks/core.framework/common/route-common.component.ts

To use this reducer successfully with NativeScript however, we need to remove the dependency on `window` or at least grab `window` via DI so an appropriate substitute could be provided for in a native environment where `window` doesn't exist.

Problem:
https://github.com/CodeSequence/ngrx-store-router/blob/master/src/reducer.ts#L4

Any ideas?

**Comment by brandonroberts** [comment]
This is something I have been thinking about also. What I was trying to avoid was dispatching a `Navigated` action on initial load but their may not be away around it since their the router URL is being emitted at the end of the navigation cycle. This is why I was using the `window.location` to compare it against the initial URL emitted by the router subscription. I would be fine to just let it dispatch the initial action with the current URL using `location.path()`. This would eliminate the dependence on `window` and would still allow for navigating back to the initial URL.

Thoughts?

**Comment by brandonroberts** [comment]
I pushed version 0.0.6 without a dependency on `window` and stores the initial URL in an init action. If you have any issues with it, let me know.

**Comment by NathanWalker** [comment]
Thanks! I'll try that soon.

**Comment by NathanWalker** [comment]
@brandonroberts works great in NativeScript now :+1:  Thanks.
Btw, I am now using your plugin completely integrated here:
https://github.com/NathanWalker/angular2-seed-advanced

I'm sure you already know this, but the state to handle `navigating: true` is never called.
We may be able to add a handler that would hook into something like this:

```
routerCanDeactivate(next: ComponentInstruction, prev: ComponentInstruction) {
    this.store.dispatch({ type: RouterActions.navigating, payload: {url: next.url} });
    return true;
  }
```

Comes from a Components `CanDeactivate` lifecycle hook. Not sure how best to integrate something like that here.

**Comment by brandonroberts** [comment]
Cool! My intention for that action was that it could be used to trigger navigation since the router doesn't  emit that information when navigation begins. It could be used it with a directive and dispatch an navigating action when `router.navigating` changes to true, but there isn't currently a way to get the attempted url without patching the router to generate the URL from in instruction.
